### ISSUE TITLE
[Forge - 1.19.2] "Equivalent Additions (equivadds) encountered an error during the sided_setup event phase"

### ISSUE THREAD

**Issue by TacoLite** [dragon-forge/EquivalentAdditions#1]
Hello! Big fan of your mods, so I wanted to *hopefully* provide some assistance with this ticket. I hope this is the correct place to put this report.

Currently, I am experiencing an error that I have isolated to Equivalent Addition's latest version for 1.19.2 on Forge. This error occurs just before reaching the main menu. I have provided a screenshot of the error message and the associated crash log below.

If there is anything else I can do to help, please let me know.
- TacoLite

[crash-2023-01-25_21.01.56-fml.txt](https://github.com/dragon-forge/EquivalentAdditions/files/10505824/crash-2023-01-25_21.01.56-fml.txt)

![mc equivalent additions 1-19-2 error](https://user-images.githubusercontent.com/20021871/214743688-6930ea05-79c3-42b1-ac0b-e46397d6e565.PNG)

**Comment by Zeitheron** [comment]
Just pushed out a new [HammerLib v19.3.56](https://www.curseforge.com/minecraft/mc-mods/hammer-lib/files/4365804).
Please try that version out and see if the error persists!

**Comment by TacoLite** [comment]
That update worked for me first try! I was able to load to the main menu and enter a world. I then interacted with a collector and some items; and experienced no issues. You work quick. Thank you for your diligence.
